baseurl: "/lod-vocabulary" # the subpath of your site, e.g. /blog
url: "https://berlin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
true_url:
  "https://berlin.github.io" # This duplication is necessary to make relative links work when
  # running the Jekyll-Site locally, when `url` is replaced with something like http://localhost:4000

dataset_url: "/lod-vocabulary/"
dataset_breadcrumb: "Datensatz"
cbd_folder: "cbds/"

exclude:
  - bin/
  - data/
  - conf/
  - README.md
  - Makefile
plugins:
  - jekyll-rdf

# Jekyll RDF settings
jekyll_rdf:
  path: "data/temp/all.nt"
  restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?predicate ?object FILTER(STRSTARTS(STR(?resourceUri), 'https://berlinonline.github.io/lod-berlin-bo')) }"
  default_template: "default"
  class_template_mappings:
    "http://rdfs.org/ns/void#Dataset": "dataset"
    "https://schema.org/Organization": "organization"
    "https://berlin.github.io/lod-vocabulary/ImprintPage": "imprint"
